<robot name="imu" xmlns:xacro="http://wiki.ros.org/xacro">



    <xacro:property name="imu_length" value="0.04" />
    <xacro:property name="imu_radius" value="0.025" />
    <xacro:property name="imu_x" value="0.0" /> 
    <xacro:property name="imu_y" value="0.0" /> 
    <xacro:property name="imu_z" value="${base_link_height/2 + imu_length / 2}" />

    <xacro:property name="imu_m" value="0.1" /> 
    <link name="imu">
        <visual>
            <geometry>
                <mesh filename="package://six_wheel_robot/meshes/imu.dae" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://six_wheel_robot/meshes/imu.dae" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${imu_m}" r="${imu_radius}" h="${imu_length}" />
    </link>

    <joint name="imu2base_link" type="fixed">
        <parent link="base_link" />
        <child link="imu" />
        <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0.0 0.0 0.0"/>
    </joint>
    <gazebo reference="imu">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>