<robot name="laser" xmlns:xacro="http://wiki.ros.org/xacro">



    <xacro:property name="laser_length" value="0.04" />
    <xacro:property name="laser_radius" value="0.025" />
    <xacro:property name="laser_x" value="-0.15" /> 
    <xacro:property name="laser_y" value="0.0" /> 
    <xacro:property name="laser_z" value="${base_link_height/2 + laser_length / 2}" />

    <xacro:property name="laser_m" value="0.1" /> 
    <link name="laser">
        <visual>
            <geometry>
                <mesh filename="package://six_wheel_robot/meshes/rplidarA3.dae" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://six_wheel_robot/meshes/rplidarA3.dae" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />
    </link>

    <joint name="laser2base_link" type="fixed">
        <parent link="base_link" />
        <child link="laser" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0.0 0.0 0.0"/>
    </joint>
    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>