<?xml version="1.0"?>

<robot name="robot_body" 
    xmlns:xacro="http://ros.org/wiki/xacro">
    
    
    <xacro:property name="PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_link_x" value="0.5"/>
    <xacro:property name="base_link_y" value="0.25"/>
    <xacro:property name="base_link_height" value="0.05"/>
    <xacro:property name="wheel_length" value="0.025"/>    


    <!-- Another definition -->
    <xacro:property name="earth_space" value="0.045"/>
    <xacro:property name="base_footprint_radius" value="0.001" /> 


    <link name="base_footprint">
      <visual>
        <geometry>
          <sphere radius="${base_footprint_radius}" />
        </geometry>
      </visual>
    </link>

        
    <link name="base_link">
      <visual>
        <geometry>
          <box size="${base_link_x} ${base_link_y} ${base_link_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <material name="white">
          <color rgba="0.7 0.7 0.7 1" />
        </material>
      </visual>
       <collision>
        <geometry>
          <box size="${base_link_x} ${base_link_y} ${base_link_height}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <xacro:Box_inertial_matrix m="1" l="${base_link_x}" w="${base_link_y}" h="${base_link_height}" />
    </link>

    <joint name="base_link2base_footprint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 ${earth_space + base_link_height / 2 }" />
    </joint>

  
    <xacro:macro name="add_wheels" params="name wheel_radius x y z">
      <link name="${name}_wheel">
        <visual>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
          <material name="black" />
        </visual>
        <collision>
          <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}" />
          </geometry>
          <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="0.4" r="${wheel_radius}" h="${wheel_length}"/>
      
      </link>

      <joint name="${name}_wheel2base_link" type="continuous">
        <parent link="base_link" />
        <child link="${name}_wheel" />
        <origin xyz="${x} ${y} ${z}" />
        <axis xyz="0 1 0" />
      </joint>
    </xacro:macro>

    <xacro:add_wheels name="left_front" wheel_radius="0.04"  x="0.2" y="${(base_link_y + wheel_length)/2}" z="-0.05"/>
    <xacro:add_wheels name="left_mid" wheel_radius="0.06"  x="0" y="${(base_link_y + wheel_length)/2}" z="-0.03"/>
    <xacro:add_wheels name="left_rear" wheel_radius="0.04"  x="-0.2" y="${(base_link_y + wheel_length)/2}" z="-0.05"/>

    <xacro:add_wheels name="right_front" wheel_radius="0.04"  x="0.2" y="-${(base_link_y + wheel_length)/2}" z="-0.05"/>
    <xacro:add_wheels name="right_mid" wheel_radius="0.06"  x="0" y="-${(base_link_y + wheel_length)/2}" z="-0.03"/>
    <xacro:add_wheels name="right_rear" wheel_radius="0.04"  x="-0.2" y="-${(base_link_y + wheel_length)/2}" z="-0.05"/>

    
</robot>